### ISSUE TITLE
404 File not found

### ISSUE THREAD

**Issue by denisgolius** [flant/loghouse#101]
`helm repo add loghouse https://flant.github.io/loghouse/charts/`
+ 404 for https://flant.github.io/loghouse/charts/

**Comment by diafour** [comment]
@denisgolius please show `helm version` output. It looks something has changed since version 2.8.2.

```
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
$ helm repo add loghouse https://flant.github.io/loghouse/charts/     
"loghouse" has been added to your repositories
```

**Comment by paskal** [comment]
Helm v2.9.1 here, despite the http error, repo add and update works fine. I think it's false positive.
