### ISSUE TITLE
Helm chart: Clickhouse should be managed by StatefulSet instead of Deployment

### ISSUE THREAD

**Issue by dragonsmith** [flant/loghouse#118]
Hello!

Thanks a lot for such a big contribution to the K8s community!

I'm trying your Loghouse right now and I find the following strange: ClickHouse is a stateful app, yet, you manage it with a Deployment in your Helm chart.

I can provide a PR to fix that, what do you think?

Thank you!

**Comment by distol** [comment]
Yea, you are entirely right. We are misusing deployment. PR with the fix for that will be well appreciated. The hardest part, like always, is to find the proper upgrade way.

Speaking about the future, we hope that at some time there will be Clickhouse operator and we will rely on it.

**Comment by diafour** [comment]
Done in #137, released as v0.3.0.
