### ISSUE TITLE
Export in CSV file doesn't work

### ISSUE THREAD

**Issue by rjeka** [flant/loghouse#122]
Hello !
When I try to copy the search result to a CSV file, I get the error ERR_INVALID_RESPONSE

![2019-03-04 16 49 29](https://user-images.githubusercontent.com/32553160/53737643-20597800-3e9e-11e9-94e0-a919b1d59271.png)

backend version 21cca708

**Comment by Sungurik** [comment]
Same problem. HTTP 500 return and record in logs:
`/app/lib/loghouse_query/csv.rb:5:in `csv_result'`

**Comment by diafour** [comment]
I think it is fixed in v0.3.1. See #142

**Comment by rjeka** [comment]
Thanks! It works after the update.
