### ISSUE TITLE
Error deploying loghouse to GKE

### ISSUE THREAD

**Issue by jarleaase** [flant/loghouse#127]
```
 helm install -n loghouse loghouse/loghouse 
Error: validation failed: unable to recognize "": no matches for kind "CronJob" in version "batch/v2alpha1"
```

**Comment by CGuerreroCordova** [comment]
I have the same problem :(

**Comment by jhecc** [comment]
Please provide your client and cluster information as well api versions (kubectl api-versions | grep batch)

**Comment by CGuerreroCordova** [comment]
> Please provide your client and cluster information as well api versions (kubectl api-versions | grep batch)

Sorry for delay to answer, I was changed gor some months, but I still have the same problem.
`kubectl version

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:42:56Z", GoVersion:"go1.12.12", Compiler:"gc",
 Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.4-gke.22", GitCommit:"a6ba43f5a24ac29e631bb627c9b2a719c4e93638", GitTreeState:"clean", BuildDate:"2019-11-26T00:40:25Z", GoVersion:"go1.12.11b4", Comp
iler:"gc", Platform:"linux/amd64"}


kubectl cluster-info


Kubernetes master is running at https://35.239.77.232
GLBCDefaultBackend is running at https://35.239.77.232/api/v1/namespaces/kube-system/services/default-http-backend:http/proxy
KubeDNS is running at https://35.239.77.232/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
kubernetes-dashboard is running at https://35.239.77.232/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
Metrics-server is running at https://35.239.77.232/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.


kubectl api-versions | grep batch


batch/v1
batch/v1beta1`

Thanks

**Comment by diafour** [comment]
ApiVersions was updated for all resources in #137, "batch/v1beta1" is used for CronJob now.
There are more improvements, please update to v0.3.0.
