### ISSUE TITLE
Need to use helm.sh/hook-delete-policy

### ISSUE THREAD

**Issue by DavidKaz** [flant/loghouse#31]
https://github.com/flant/loghouse/blob/64d0d88d24eaf1b6aa1db9470a5a3ce1f6088cd6/charts/loghouse/templates/loghouse/loghouse-init-tables.yaml#L8

> [kube] root@kube ~ # vi loghouse/values.yaml 
> [kube] root@kube ~ # helm upgrade --namespace loghouse loghouse loghouse/
> Error: UPGRADE FAILED: jobs.batch "loghouse-init-tables" already exists
> [kube] root@kube ~ # kubectl -n loghouse delete jobs/loghouse-init-tables
> job "loghouse-init-tables" deleted
> [kube] root@kube ~ # kubectl -n loghouse delete jobs/loghouse-init-tables
> job "loghouse-init-tables" deleted
> [kube] root@kube ~ # helm upgrade --namespace loghouse loghouse loghouse/
> Release "loghouse" has been upgraded. Happy Helming!
> LAST DEPLOYED: Fri Dec  8 14:18:30 2017

**Comment by diafour** [comment]
Annotation was added in #137 and released as v0.3.0. There are more improvements, check it out!
