### ISSUE TITLE
Wrong query language definitions

### ISSUE THREAD

**Issue by RouR** [flant/loghouse#41]
Wrong query language definitions (https://github.com/flant/loghouse/blob/master/docs/ru/query-language.md)

This query
> SELECT string_fields.names,
> 	string_fields.values
> FROM
> 	logs.logs
> 
> WHERE
> 	date=today() AND   string_fields.values = '1'
> 
> Order by  timestamp
> LIMIT 100

throw 

> Code: 43, e.displayText() = DB::Exception: Illegal types of arguments (Array(String), String) of function equals, e.what() = DB::Exception

Images:
flant/loghouse-clickhouse:0.0.2
flant/loghouse-fluentd:0.0.2
flant/loghouse-tabix:0.0.2

**Comment by gsmetal** [comment]
Hello.

I didn't understand your issue. You link the Loghouse query language but show the clickhouse SQL.
What query (in the UI) did you use to achieve this SQL?

**Comment by RouR** [comment]
I use this chart - https://github.com/flant/loghouse/tree/master/charts/loghouse/templates

I use tabix with connect to clickhouse. 
I don`t have any another manual, how to use it.

**Comment by may-cat** [comment]
After loghouse installation to your kubernetes cloud, it becomes available on web:
https://image.ibb.co/efFYtH/loghouse.png
https://camo.githubusercontent.com/94097488f3ba57529c47f3bef3e3abe4a8c9e845/68747470733a2f2f63646e2e7261776769742e636f6d2f666c616e742f6c6f67686f7573652f6d61737465722f646f63732f7765622d75692d616e696d617465642e676966
You specify domain in your values.yaml file:
https://github.com/flant/loghouse/blob/master/charts/loghouse/values.yaml#L25
Query language is desined for usage in web interface. It is better to use it in Query field.

Does this solve your problem?

**Comment by RouR** [comment]
Can be closed, tnx
