### ISSUE TITLE
Make fixed version for each docker image release

### ISSUE THREAD

**Issue by yurchenkosv** [flant/loghouse#78]
For implementing new features in your app, docker image tag "latest" is not an option.
Now, I've just restart pod with loghouse-dashboard and search templates like log="%POST%" stop to working. Also, running query with that search template causes high CPU and memory usage on pod with dashboard and pod with clickhouse. 
I've tried to rollback to previous version, but can't because of update docker image in your repository with tag "latest" which overwrites previous image.

**Comment by may-cat** [comment]
Thanks for your issue.
Yes, that's a trouble. We will fix it soon.
